apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd
  labels:
     app: myfirst-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: myfirst-app

  template:
    metadata:
      labels:
        app: myfirst-app

    spec:
      containers:
      - name: myfirst-app
        image: pruthvidevops/deveops:app-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
