apiVersion: v1
kind: Service
metadata:
  name: ci-cd-service
  labels:
    app: myfirst-app
spec:
  selector:
    app: myfirst-app
    
  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
